import { formatCurrency } from "@/lib/utils"
import { DEFAULT_CURRENCY, type CurrencyCode } from "@/lib/currency"
import type { BillDetailData } from "@/lib/data-service"

export type WhatsAppBillData = BillDetailData

export function getUpiPaymentLink(
  upiId: string,
  payeeName: string,
  amount: number,
  currency: CurrencyCode = DEFAULT_CURRENCY
): string {
  const params = new URLSearchParams({
    pa: upiId,
    pn: payeeName,
    am: amount.toFixed(2),
    cu: currency,
    tn: "Electricity Bill Share",
  })
  return `upi://pay?${params.toString()}`
}

export function getWhatsAppUrl(data: WhatsAppBillData, currency: CurrencyCode = DEFAULT_CURRENCY): string {
  const fromDate = new Date(data.billingPeriod.from).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  })
  const toDate = new Date(data.billingPeriod.to).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  })

  let text = `*Electricity Bill Split*\n`
  text += `${fromDate} — ${toDate}\n\n`

  text += `*── Bill Summary ──*\n`
  text += `Total Bill: *${formatCurrency(data.totalBill, currency)}*\n`
  text += `Total Units: ${data.totalUnits}\n`
  text += `Per Unit Price: ${formatCurrency(data.computed.perUnitPrice, currency)}\n\n`

  text += `*── Submeter Readings ──*\n`
  for (const [slug, reading] of Object.entries(data.submeterReadings)) {
    const units = data.computed.areaUnits[slug] || 0
    const cost = data.computed.areaCosts[slug] || 0
    const label = slug.charAt(0).toUpperCase() + slug.slice(1)
    text += `*${label}:* ${reading.previous} → ${reading.current} = ${units} units (${formatCurrency(cost, currency)})\n`
  }
  text += `*Common:* ${data.computed.commonUnits} units (${formatCurrency(data.computed.commonCost, currency)})\n\n`

  text += `*── Individual Shares ──*\n`
  data.splits.forEach((s) => {
    text += `\n*${s.roommateName}* (${s.area})\n`
    text += `   Days: ${s.daysStayed} | Share: ${s.areaSharePercent}%\n`
    text += `   Area: ${formatCurrency(s.areaCost, currency)} + Common: ${formatCurrency(s.commonCost, currency)}\n`
    text += `   *Total: ${formatCurrency(s.totalAmount, currency)}*\n`
  })

  text += `\n_Generated by SplitWatt_ - https://electricity-bill-split.vercel.app`

  return `https://wa.me/?text=${encodeURIComponent(text)}`
}

export function getIndividualWhatsAppUrl(
  data: WhatsAppBillData,
  phoneNumber: string,
  upiId?: string,
  upiPayeeName?: string,
  currency: CurrencyCode = DEFAULT_CURRENCY
): string {
  const fromDate = new Date(data.billingPeriod.from).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  })
  const toDate = new Date(data.billingPeriod.to).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  })

  let text = `*Electricity Bill Split*\n`
  text += `${fromDate} — ${toDate}\n\n`

  text += `*── Bill Summary ──*\n`
  text += `Total Bill: *${formatCurrency(data.totalBill, currency)}*\n`
  text += `Total Units: ${data.totalUnits}\n`
  text += `Per Unit Price: ${formatCurrency(data.computed.perUnitPrice, currency)}\n\n`

  text += `*── Submeter Readings ──*\n`
  for (const [slug, reading] of Object.entries(data.submeterReadings)) {
    const units = data.computed.areaUnits[slug] || 0
    const cost = data.computed.areaCosts[slug] || 0
    const label = slug.charAt(0).toUpperCase() + slug.slice(1)
    text += `*${label}:* ${reading.previous} → ${reading.current} = ${units} units (${formatCurrency(cost, currency)})\n`
  }
  text += `*Common:* ${data.computed.commonUnits} units (${formatCurrency(data.computed.commonCost, currency)})\n\n`

  text += `*── Individual Shares ──*\n`
  data.splits.forEach((s) => {
    text += `\n*${s.roommateName}* (${s.area})\n`
    text += `   Days: ${s.daysStayed} | Share: ${s.areaSharePercent}%\n`
    text += `   Area: ${formatCurrency(s.areaCost, currency)} + Common: ${formatCurrency(s.commonCost, currency)}\n`
    text += `   *Total: ${formatCurrency(s.totalAmount, currency)}*\n`

    // Add UPI payment link for this roommate if UPI is configured
    if (upiId && upiPayeeName) {
      const upiLink = getUpiPaymentLink(upiId, upiPayeeName, s.totalAmount, currency)
      text += `\n*── Pay Your Share ──*\n`
      text += `Tap to pay *${formatCurrency(s.totalAmount, currency)}*\n`
      text += `${upiLink}\n`
    }
  })

  text += `\n_Generated by SplitWatt_ - https://electricity-bill-split.vercel.app`

  // Normalize phone number (remove +, spaces, dashes)
  const normalizedPhone = phoneNumber.replace(/[\s\+\-]/g, "")
  return `https://wa.me/${normalizedPhone}?text=${encodeURIComponent(text)}`
}
