import { formatCurrency } from "@/lib/utils"

export interface WhatsAppBillData {
  billingPeriod: { from: string; to: string }
  totalBill: number
  totalUnits: number
  submeterReadings: {
    hall: { previous: number; current: number }
    room: { previous: number; current: number }
  }
  computed: {
    perUnitPrice: number
    hallUnits: number
    roomUnits: number
    commonUnits: number
    hallCost: number
    roomCost: number
    commonCost: number
  }
  splits: {
    roommateName: string
    area: string
    daysStayed: number
    areaSharePercent: number
    areaCost: number
    commonCost: number
    totalAmount: number
  }[]
}

export function getWhatsAppUrl(data: WhatsAppBillData): string {
  const fromDate = new Date(data.billingPeriod.from).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  })
  const toDate = new Date(data.billingPeriod.to).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  })

  let text = `*Electricity Bill Split*\n`
  text += `${fromDate} — ${toDate}\n\n`

  text += `*── Bill Summary ──*\n`
  text += `Total Bill: *${formatCurrency(data.totalBill)}*\n`
  text += `Total Units: ${data.totalUnits}\n`
  text += `Per Unit Price: ${formatCurrency(data.computed.perUnitPrice)}\n\n`

  text += `*── Submeter Readings ──*\n`
  text += `*Hall:* ${data.submeterReadings.hall.previous} → ${data.submeterReadings.hall.current} = ${data.computed.hallUnits} units (${formatCurrency(data.computed.hallCost)})\n`
  text += `*Room:* ${data.submeterReadings.room.previous} → ${data.submeterReadings.room.current} = ${data.computed.roomUnits} units (${formatCurrency(data.computed.roomCost)})\n`
  text += `*Common:* ${data.computed.commonUnits} units (${formatCurrency(data.computed.commonCost)})\n\n`

  text += `*── Individual Shares ──*\n`
  data.splits.forEach((s) => {
    text += `\n*${s.roommateName}* (${s.area})\n`
    text += `   Days: ${s.daysStayed} | Share: ${s.areaSharePercent}%\n`
    text += `   Area: ${formatCurrency(s.areaCost)} + Common: ${formatCurrency(s.commonCost)}\n`
    text += `   *Total: ${formatCurrency(s.totalAmount)}*\n`
  })

  text += `\n_Generated by SplitWatt_`

  return `https://wa.me/?text=${encodeURIComponent(text)}`
}

export function getIndividualWhatsAppUrl(
  data: WhatsAppBillData,
  phoneNumber: string
): string {
  const fromDate = new Date(data.billingPeriod.from).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  })
  const toDate = new Date(data.billingPeriod.to).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  })

  let text = `*Electricity Bill Split*\n`
  text += `${fromDate} — ${toDate}\n\n`

  text += `*── Bill Summary ──*\n`
  text += `Total Bill: *${formatCurrency(data.totalBill)}*\n`
  text += `Total Units: ${data.totalUnits}\n`
  text += `Per Unit Price: ${formatCurrency(data.computed.perUnitPrice)}\n\n`

  text += `*── Submeter Readings ──*\n`
  text += `*Hall:* ${data.submeterReadings.hall.previous} → ${data.submeterReadings.hall.current} = ${data.computed.hallUnits} units (${formatCurrency(data.computed.hallCost)})\n`
  text += `*Room:* ${data.submeterReadings.room.previous} → ${data.submeterReadings.room.current} = ${data.computed.roomUnits} units (${formatCurrency(data.computed.roomCost)})\n`
  text += `*Common:* ${data.computed.commonUnits} units (${formatCurrency(data.computed.commonCost)})\n\n`

  text += `*── Individual Shares ──*\n`
  data.splits.forEach((s) => {
    text += `\n*${s.roommateName}* (${s.area})\n`
    text += `   Days: ${s.daysStayed} | Share: ${s.areaSharePercent}%\n`
    text += `   Area: ${formatCurrency(s.areaCost)} + Common: ${formatCurrency(s.commonCost)}\n`
    text += `   *Total: ${formatCurrency(s.totalAmount)}*\n`
  })

  text += `\n_Generated by SplitWatt_`

  // Normalize phone number (remove +, spaces, dashes)
  const normalizedPhone = phoneNumber.replace(/[\s\+\-]/g, "")
  return `https://wa.me/${normalizedPhone}?text=${encodeURIComponent(text)}`
}
