import { formatCurrency, formatDate } from "@/lib/utils"
import { DEFAULT_CURRENCY, type CurrencyCode } from "@/lib/currency"
import { config } from "@/lib/config"
import type { BillDetailData, FlatData } from "@/lib/data-service"

interface BillSnapshotCardProps {
  bill: BillDetailData
  flat: FlatData | null
  currency?: CurrencyCode
}

const s = {
  wrap: {
    fontFamily: "Arial, Helvetica, sans-serif",
    background: "#fff",
    color: "#111",
    padding: "28px 32px",
    width: "780px",
    fontSize: "14px",
    lineHeight: "1.5",
  } as React.CSSProperties,
  title: {
    fontSize: "22px",
    fontWeight: "bold",
    marginBottom: "2px",
  } as React.CSSProperties,
  subtitle: {
    fontSize: "13px",
    color: "#666",
    marginBottom: "20px",
  } as React.CSSProperties,
  summaryGrid: {
    display: "flex",
    gap: "12px",
    marginBottom: "24px",
  } as React.CSSProperties,
  summaryCard: {
    flex: 1,
    background: "#f5f5f5",
    borderRadius: "6px",
    padding: "12px 10px",
    textAlign: "center" as const,
  },
  summaryLabel: {
    fontSize: "11px",
    color: "#777",
    marginBottom: "4px",
  } as React.CSSProperties,
  summaryValue: {
    fontSize: "17px",
    fontWeight: "bold",
  } as React.CSSProperties,
  sectionTitle: {
    fontSize: "14px",
    fontWeight: "bold",
    borderBottom: "1px solid #ddd",
    paddingBottom: "6px",
    marginBottom: "10px",
  } as React.CSSProperties,
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "13px",
  },
  th: {
    background: "#f5f5f5",
    padding: "8px 10px",
    fontWeight: "bold",
    borderBottom: "2px solid #ddd",
  } as React.CSSProperties,
  thRight: {
    background: "#f5f5f5",
    padding: "8px 10px",
    fontWeight: "bold",
    borderBottom: "2px solid #ddd",
    textAlign: "right" as const,
  },
  td: {
    padding: "8px 10px",
    borderBottom: "1px solid #eee",
  } as React.CSSProperties,
  tdRight: {
    padding: "8px 10px",
    borderBottom: "1px solid #eee",
    textAlign: "right" as const,
  },
  tdBold: {
    padding: "8px 10px",
    borderBottom: "1px solid #eee",
    textAlign: "right" as const,
    fontWeight: "bold",
  },
  footer: {
    marginTop: "20px",
    fontSize: "11px",
    color: "#aaa",
    textAlign: "right" as const,
  },
}

export function BillSnapshotCard({ bill, flat, currency = DEFAULT_CURRENCY }: BillSnapshotCardProps) {
  const getAreaLabel = (slug: string) => flat?.areas.find((a) => a.slug === slug)?.label || slug

  return (
    <div style={s.wrap}>
      <div style={s.title}>Electricity Bill Split</div>
      <div style={s.subtitle}>
        {formatDate(bill.billingPeriod.from)} &mdash; {formatDate(bill.billingPeriod.to)}
      </div>

      <div style={s.summaryGrid}>
        {[
          { label: "Total Bill", value: formatCurrency(bill.totalBill, currency) },
          { label: "Total Units", value: `${bill.totalUnits} units` },
          { label: "Per Unit Price", value: formatCurrency(bill.computed.perUnitPrice, currency) },
          { label: "Common Units", value: `${bill.computed.commonUnits} units` },
        ].map(({ label, value }) => (
          <div key={label} style={s.summaryCard}>
            <div style={s.summaryLabel}>{label}</div>
            <div style={s.summaryValue}>{value}</div>
          </div>
        ))}
      </div>

      <div style={s.sectionTitle}>Individual Distribution</div>
      <table style={s.table}>
        <thead>
          <tr>
            <th style={s.th}>Name</th>
            <th style={s.th}>Area</th>
            <th style={s.thRight}>Days</th>
            <th style={s.thRight}>Area Share</th>
            <th style={s.thRight}>Area Cost</th>
            <th style={s.thRight}>Common</th>
            <th style={s.thRight}>Total</th>
          </tr>
        </thead>
        <tbody>
          {bill.splits.map((split, i) => (
            <tr key={i}>
              <td style={s.td}>{split.roommateName}</td>
              <td style={s.td}>{getAreaLabel(split.area)}</td>
              <td style={s.tdRight}>{split.daysStayed}</td>
              <td style={s.tdRight}>{split.areaSharePercent}%</td>
              <td style={s.tdRight}>{formatCurrency(split.areaCost, currency)}</td>
              <td style={s.tdRight}>{formatCurrency(split.commonCost, currency)}</td>
              <td style={s.tdBold}>{formatCurrency(split.totalAmount, currency)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={s.footer}>Generated by {config.app.name}</div>
    </div>
  )
}
