"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { useDataService } from "@/lib/guest-context"
import { useCurrency } from "@/lib/currency-context"
import { toast } from "sonner"
import { generateBillFilename } from "@/lib/utils"
import { generateBillImageDataUrl, generateBillImageBlob } from "@/lib/generate-bill-image"
import { config } from "@/lib/config"
import type { BillDetailData, FlatData } from "@/lib/data-service"
import {
  trackExportPDF,
  trackExportPDFFailed,
  trackExportImage,
  trackExportImageFailed,
  trackShareWhatsApp,
} from "@/lib/analytics"

interface ExportActionsProps {
  billId: string
  bill: BillDetailData
  flat: FlatData | null
}

export function ExportActions({ billId, bill, flat }: ExportActionsProps) {
  const { service } = useDataService()
  const { currency } = useCurrency()
  const [exporting, setExporting] = useState<string | null>(null)

  async function handlePdfDownload() {
    setExporting("pdf")
    try {
      const blob = await service.generatePdfBlob(billId, currency)
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = generateBillFilename(bill.billingPeriod.from, bill.billingPeriod.to, "pdf")
      a.click()
      URL.revokeObjectURL(url)
      trackExportPDF(billId)
      toast.success("PDF downloaded")
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : "Unknown error"
      trackExportPDFFailed(billId, errorMsg)
      toast.error("Failed to download PDF")
    }
    setExporting(null)
  }

  async function handleImageDownload() {
    setExporting("image")
    try {
      const dataUrl = await generateBillImageDataUrl(bill, flat, currency)
      const a = document.createElement("a")
      a.href = dataUrl
      a.download = generateBillFilename(bill.billingPeriod.from, bill.billingPeriod.to, "png")
      a.click()
      trackExportImage(billId)
      toast.success("Image downloaded")
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : "Unknown error"
      trackExportImageFailed(billId, errorMsg)
      toast.error("Failed to download image")
    }
    setExporting(null)
  }

  async function handleWhatsAppShare() {
    setExporting("whatsapp")
    try {
      const blob = await generateBillImageBlob(bill, flat, currency)
      const filename = generateBillFilename(bill.billingPeriod.from, bill.billingPeriod.to, "png")

      const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? config.app.url
      let caption = `_Generated by ${config.app.name}_ - ${appUrl}`
      if (flat?.upiId && flat?.upiPayeeName) {
        caption += `\nPay to: ${flat.upiPayeeName} (${flat.upiId})`
      }

      const isMobile = /Android|iPhone|iPad|iPod/i.test(navigator.userAgent)
      const file = new File([blob], filename, { type: "image/png" })

      if (isMobile && navigator.canShare?.({ files: [file] })) {
        // Mobile: native share sheet — WhatsApp appears with image attached
        await navigator.share({ files: [file], text: caption })
      } else {
        // Desktop: just download the image
        const objUrl = URL.createObjectURL(blob)
        const a = document.createElement("a")
        a.href = objUrl
        a.download = filename
        a.click()
        URL.revokeObjectURL(objUrl)
        toast.success("Image downloaded")
      }

      trackShareWhatsApp(billId, "group")
    } catch (err) {
      if (err instanceof Error && err.name !== "AbortError") {
        toast.error("Failed to share")
      }
    }
    setExporting(null)
  }

  return (
    <div className="flex flex-wrap gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={handlePdfDownload}
        disabled={exporting === "pdf"}
      >
        {exporting === "pdf" ? "Generating..." : "Download PDF"}
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={handleImageDownload}
        disabled={exporting === "image"}
      >
        {exporting === "image" ? "Capturing..." : "Download Image"}
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={handleWhatsAppShare}
        disabled={exporting === "whatsapp"}
      >
        {exporting === "whatsapp" ? "Preparing..." : "Share on WhatsApp"}
      </Button>
    </div>
  )
}
